$kind: http-request
name: "product: getProducts"
url: localhost:3007/product/all?order=createdAt&page=1&limit=3&productCollection=DISH
method: GET
queryParams:
  - key: order
    value: createdAt
  - key: page
    value: "1"
  - key: limit
    value: "3"
  - key: productCollection
    value: DISH
order: 4503388874432990
